default:
  image: tensorflow/tensorflow
  cache:
    paths:
      - .pip-cache/
  before_script:
    - python --version
    - pip install --upgrade pip
    - pip install build
    - pip install -r requirements.txt
  tags:
    - plmshift

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - python -m build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - pip install pytest
    - pytest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"

pages:
  stage: deploy
  script:
    - pip install -U sphinx
    - sphinx-build -b html doc/ public/
  only:
    - main
  artifacts:
    paths:
      - public
