image: tensorflow/tensorflow

stages:
  - deploy

pages:
  stage: deploy
  script:
    - pip install -r requirements.txt
    - pip install -U sphinx
    - sphinx-build -b html doc/ public/
  only:
    - main
  artifacts:
    paths:
      - public
  tags:
    - plmshift
